### ISSUE TITLE
Dividers

### ISSUE THREAD

**Issue by MoonshineSG** [foosel/OctoPrint#1084]
What were you doing?
add dividers into the system menu

What did you expect to happen?
menu to be split in 3 sections

```
system:
  actions:
  - action: printer on
    command: gpio -g write 24 1
    name: Turn printer ON
  - action: camera on
    command: gpio -g write 32 1;gpio -g write 23 1
    name: Turn IR lights ON
  - action: divider
  - action: printer off
    command: gpio -g write 24 0
    confirm: You are about to stop the printer.
    name: Turn printer OFF ☂
  - action: camera off
    command: gpio -g write 32 0;gpio -g write 23 0
    name: Turn IR lights OFF
  - action: divider
  - action: shutdown
    command: sudo shutdown -h now
    confirm: You are about to shutdown the system.
    name: Shutdown ☂
  - action: reboot
    command: sudo shutdown -r now
    confirm: You are about to reboot the system
    name: Reboot  ☂
  - action: restart
    command: sudo service octoprint restart
    confirm: You are about to restart OctoPrint
    name: Restart OctoPrint  ☂
```

What happened instead?
only first "- action: divider" works

![image](https://cloud.githubusercontent.com/assets/687747/10424627/35e44306-7103-11e5-815f-679ea36b9477.png)

Branch & Commit or Version of OctoPrint:
latest (and some prev versions)

Printer model & used firmware incl. version
(if applicable - always include if unsure):
irelevant

Browser and Version of Browser, Operating 
System running Browser (if applicable - always 
include if unsure):
safari/chrome, but would fail on any...

Link to octoprint.log on gist.github.com or pastebin.com
(ALWAYS INCLUDE AND DO NOT TRUNCATE):
n/a

Link to contents of terminal tab or serial.log on 
gist.github.com or pastebin.com (if applicable - always 
include if unsure or reporting communication issues AND
DO NOT TRUNCATE):
n/a

Link to contents of Javascript console in the browser 
on gist.github.com or pastebin.com or alternatively a
screenshot (if applicable - always include if unsure
or reporting UI issues):
n/a

Screenshot(s) showing the problem (if applicable - always
include if unsure or reporting UI issues):

I have read the FAQ.

Note: this used to work, but I am not sure when it stopped working...
