### ISSUE TITLE
custom control param

### ISSUE THREAD

**Issue by MoonshineSG** [foosel/OctoPrint#1085]
What were you doing?
use custom control with parameters

What did you expect to happen?
parameter to be replace by actual value

```
[...]   
    - commands:
      - M851 Z-%(distance)
      - M500
      - M501
      input:
      - default: 0
        name: Set offset
        parameter: distance
        slider: false
```

![image](https://cloud.githubusercontent.com/assets/687747/10424673/bf360ac2-7103-11e5-9504-c8de336f75a1.png)

What happened instead?
parameter name used instead

![image](https://cloud.githubusercontent.com/assets/687747/10424689/e368f562-7103-11e5-8bfd-d807032226d8.png)

Branch & Commit or Version of OctoPrint:
Version: 1.3.0.dev530+g1bf46d6 (HEAD branch)

Printer model & used firmware incl. version
(if applicable - always include if unsure):
irrelevant

Browser and Version of Browser, Operating 
System running Browser (if applicable - always 
include if unsure):
irrelevant

Link to octoprint.log on gist.github.com or pastebin.com
(ALWAYS INCLUDE AND DO NOT TRUNCATE):
n/a

Link to contents of terminal tab or serial.log on 
gist.github.com or pastebin.com (if applicable - always 
include if unsure or reporting communication issues AND
DO NOT TRUNCATE):
n/a

Link to contents of Javascript console in the browser 
on gist.github.com or pastebin.com or alternatively a
screenshot (if applicable - always include if unsure
or reporting UI issues):
no error gets reported

Screenshot(s) showing the problem (if applicable - always
include if unsure or reporting UI issues):
see above

I have read the FAQ.

**Comment by foosel** [comment]
Your parameter format is missing the actual format string after the parameter name. What happens if you try "%(distance)d"?

**Comment by MoonshineSG** [comment]
Sorry, the cat ate it !!   :D 

But doesn't help... 
![image](https://cloud.githubusercontent.com/assets/687747/10425218/453b53a8-7108-11e5-8248-7db8f513a3d0.png)

**Comment by foosel** [comment]
@Salandora could you take a look at this? Or it will have to wait until next week.

**Comment by Salandora** [comment]
Interesting. Will take a look.

**Comment by Salandora** [comment]
Pushed a commit that fixes the problem.

**Comment by MoonshineSG** [comment]
works. but with `%(distance)s`

otherwise it gives "TypeError: %d format: a number is required, not unicode"

**Comment by MoonshineSG** [comment]
not sure if this is related.... I tested a custom control that calls a script which contains parameters... 

```
    - input:
      - default: X
        name: Axis
        parameter: axis
        slider: false
      - default: 10
        name: Distance
        parameter: test_length
        slider:
          max: 20
          min: 1
      - default: 5
        name: Repeat
        parameter: repetitions
        slider:
          max: 20
          min: 2
      name: Go
      script: custom/repeatability.gcode
```

~/.octoprint/scripts/gcode/custom/repeatability.gcode
```
G91

{% for n in range(parameters.repetitions) %}
  G1 {{ parameters.axis }}{{ parameters.test_length }} F1000
  G4 S1
  G1 {{ parameters.axis }}-{{ parameters.test_length }} F1000
  G4 S1
{% endfor %}

G90
```

JS console throws a HTTP 404 error with message "Unknown script: custom/repeatability.gcode"

Again, this used to work....
