### ISSUE TITLE
OctoPi changes config.yaml rearranges and Modifies events

### ISSUE THREAD

**Issue by WVUTampaAlum** [foosel/OctoPrint#1312]
I am trying to setup octopi to send me a picture of the object when the print is completed.  I running octopi and Version: 1.2.10 (master branch).  I have followed the guide on (https://github.com/foosel/OctoPrint/wiki/Cookbook:-Useful-Eventhooks) .  I have tried 4 times and cannot get it to send me an email but running the same 'command' in terminal I get the email with pic attached.  What I have found from this is that octoprint is moving the section I enter (I put it at the bottom) and completely change the events.

As a test I entered the following from the wiki.  I then restarted octoprint server made 0 changes and viewed config.yaml.  It was then completely changed around.

Entered in Events section/ from wiki:
```
events:
  enabled: True
  subscriptions:
  - event: Disconnected
    command: python ~/growl.py -t mygrowlserver -d "Lost connection to printer" -a OctoPrint -i http://raspi/Octoprint_logo.png
    type: system
    enabled: false
  - event: PrintStarted
    command: python ~/growl.py -t mygrowlserver -d "Starting {file}" -a OctoPrint -i http://raspi/Octoprint_logo.png
    type: system
  - event: PrintDone
    command: python ~/growl.py -t mygrowlserver -d "Completed {file}" -a OctoPrint -i http://raspi/Octoprint_logo.png
    type: system
```

Restart octoprint and config.yaml is changed to (its moved events and now added dashes for command line):

```
events:
  enabled: true
  subscriptions:
  - command: python ~/growl.py -t mygrowlserver -d "Lost connection to printer" -a
      OctoPrint -i http://raspi/Octoprint_logo.png
    enabled: false
    event: Disconnected
    type: system
  - command: python ~/growl.py -t mygrowlserver -d "Starting {file}" -a OctoPrint
      -i http://raspi/Octoprint_logo.png
    event: PrintStarted
    type: system
  - command: python ~/growl.py -t mygrowlserver -d "Completed {file}" -a OctoPrint
      -i http://raspi/Octoprint_logo.png
    event: PrintDone
    type: system
```

**Comment by GitIssueBot** [comment]
Hi @WVUTampaAlum,

It looks like there is some information missing from your bug report that will be needed in order to solve the problem. Please take a look at the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md) which will provide you with a template to fill out here so that your bug report is ready to be investigated (I promise I'll go away then too!).

If you did not intend to report a bug, please take special note of the title format to use as described in the [Contribution Guidelines](https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md).

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two weeks (until 2016-04-29 16:00) I'll close this ticket so it doesn't clutter the bug tracker. This is nothing personal, so please just be considerate and help the maintainers solve this problem quickly by following the guidelines linked above. Remember, the less time the devs have to spend running after information on tickets, the more time they have to actually solve problems and add awesome new features. Thank you!

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being, so don't expect any replies from me :) Your ticket is read by humans too, I'm just not one of them.

**Comment by markwal** [comment]
Yes. OctoPrint reads config.yaml into a dictionary.  If it decides to write any settings, it rewrites the entire file by re-exporting the settings dictionary as yaml.

Typically, the dictionaries get sorted by key.

**Comment by markwal** [comment]
Github markdown also changed the snippets you posted here.  You can put triple quotes around code to avoid that difficulty.  I've edited your post so that the snippets are easier to read.

In any case, this rewriting of the config.yaml is expected and in the example you gave, will have no effect on the run time (since the internal dictionaries for each event will work like they did before).  It's merely putting each dictionary in that event array in key order (command, event, type) and since those keys are looked up by key, it's the same either way around.

**Comment by WVUTampaAlum** [comment]
The real problem I face is that it appears octoprint does not execute events in config.yaml presumably because it rewrites everything.  Are you saying the rewritten code is correct?  Is there any way to debug config.yaml/events and what not?

Here is what I want.
events:
  subscriptions:
  - event: PrintDone
  command: curl -o /tmp/printDone.jpg "http://localhost:8080/?action=snapshot" && mpack -s "Print of {file} finished" /tmp/printDone.jpg <your mail address>
  type: system

That code doesn't appear to run.  There is not jpg and I never get any email.  I can run in terminal and code executes fine.
command: curl -o /tmp/printDone.jpg "http://localhost:8080/?action=snapshot" && mpack -s "Print of {file} finished" /tmp/printDone.jpg <your mail address>

**Comment by markwal** [comment]
Two things that might help:

1. You have to get the indentation precisely correct.  Yaml insists, like python, that precisely the right number of spaces and/or tabs match all of the other items at the same level.  Notice in your earlier example, the event item dictionary keys were lined up with each other, not with the "-" marking the array entry.
2. You need to get OctoPrint to read it after you've add your entry.  You do this by restarting OctoPrint: "sudo service octoprint restart".  If you hit "Save" on settings before the restart, you'r new entry will be overwritten.  A very cautious approach would be to stop octoprint, edit, and then restart:

```
sudo service octoprint stop
nano ~/.octoprint/config.yaml
sudo service octoprint restart
```

```
events:
  subscriptions:
  - event: PrintDone
    command: curl -o /tmp/printDone.jpg "http://localhost:8080/?action=snapshot" && mpack -s "Print of {file} finished" /tmp/printDone.jpg <your mail address>
    type: system
```

Also, the command runs in the context of the pi user, so the /tmp folder must be writable by that user.  I assume that you've got that part working since you said you can run from the teminal (without sudo).
