### ISSUE TITLE
OctoPrint saves temperature presets with single quotes - they are not strings

### ISSUE THREAD

**Issue by ururk** [foosel/OctoPrint#2520]
#### What were you doing?

Trying to set a preset temperature for a new material (PLA/PHA).

1. After logging in, click on Settings icon
2. Under **Printer**, click **Temperatures**
3. Click the **+** symbol
4. Type in:
    **Name:** PLA/PHA
    **Extruder:** 180 
    **Bed:** 50

5. Click **Save**

#### What did you expect to happen?

I expected OctoPrint to save the int values to the yaml config file without quotes - and the API call to return an int instead of a string. From OctoPrint's yaml config file, I expect this output:

```yaml
temperature:
  profiles:
  - bed: 100
    extruder: 210
    name: ABS
  - bed: 50
    extruder: 205
    name: PLA
  - bed: 50
    extruder: 180
    name: PLA/PHA
```
#### What happened instead?

Instead, this is what it generates for the temperature section:

```yaml
temperature:
  profiles:
  - bed: 100
    extruder: 210
    name: ABS
  - bed: 50
    extruder: 205
    name: PLA
  - bed: '50'
    extruder: '180'
    name: PLA/PHA
```

#### Did the same happen when running OctoPrint in safe mode?

Yes

#### Version of OctoPrint

1.3.6

#### Operating System running OctoPrint

OctoPi 0.14.0

#### Printer model & used firmware incl. version

Not applicable

#### Browser and version of browser, operating system running browser

Safari 11.0.3 (13604.5.6)
Chrome 65.0.3325.181

#### Link to octoprint.log

https://gist.github.com/ururk/9b5101268dc48680914f710ecdbce4f4

#### Link to contents of terminal tab or serial.log

https://gist.github.com/ururk/5d3b3a06503c8ed3160fd5cc2fc020a5

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.
