### ISSUE TITLE
M118 not received

### ISSUE THREAD

**Issue by p-r-o-m-e-t-h-e-u-s** [foosel/OctoPrint#3110]
#### What were you doing?

I've the following addition to Marlin 2.0 / CUSTOM_USER_MENUS:

 ```
  #define USER_DESC_1 "Light on/off"
  #define USER_GCODE_1 "M118 A1 action:light"
```

When execute the menu from my LCD Display, the M118 does not seems to be received (no entry in the serial log or web terminal).

#### What did you expect to happen?
I would expect to receive the command and some defined "Action Command Definition" is been triggered. 
#### What happened instead?
But the action command is never executed.

```
actioncommands:
    command_definitions:
    - action: reset
      command: sudo shutdown now -r
      enabled: true
      type: system
    - action: light
      command: sudo sispmctl -d 0 -t 2
      enabled: true
      type: system
```

#### Did the same happen when running OctoPrint in safe mode?
Yes

#### Version of OctoPrint
1.3.10

#### Operating System running OctoPrint
OctoPi

#### Printer model & used firmware incl. version
Marlin 2.0

#### Browser and version of browser, operating system running browser
-

#### Link to octoprint.log
-

#### Link to contents of terminal tab or serial.log
No relevant output

#### Link to contents of Javascript console in the browser
-

#### Screenshot(s)/video(s) showing the problem:
-

I have read the FAQ.
