### ISSUE TITLE
[1.4.0rc4] Autologin via IP address & disabled access control is broken due to return to forcelogin view

### ISSUE THREAD

**Issue by foosel** [foosel/OctoPrint#3434]
Looks like the auto logon feature is broken again.
![image](https://user-images.githubusercontent.com/6481341/73284444-df283000-41f4-11ea-910e-123ea6d52583.png)
Same wih IP:
![image](https://user-images.githubusercontent.com/6481341/73284595-1bf42700-41f5-11ea-8d80-827032bbe881.png)

```
nas@service-uplink:~$ cat .octoprint/config.yaml
accessControl:
    autologinAs: admin
    autologinLocal: true
    localNetworks:
    - 127.0.0.1/24
    - 192.168.1.0/24
    salt: TaRRqLPIYxxxxxxxxxxxxxxxxxxxxxx
```

_Originally posted by @schnello in https://github.com/foosel/OctoPrint/issues/3432#issuecomment-579340581_
