### ISSUE TITLE
[Request] add speed & flow multiply option

### ISSUE THREAD

**Issue by MLWORKX** [foosel/OctoPrint#777]
- Sometimes it would be really helpfull to have a speed & flow multiply option as you have on RepetierHost (see picture).
- as I have a dual head printer it would be nice to have a seperate flow multiply for extruder 0 and 1

(currently using 1.2.0-dev-480-geb4156c (devel branch))

![octo](https://cloud.githubusercontent.com/assets/4218023/6309480/26f2f7ce-b94e-11e4-9b1a-0ae302797dac.png)

**Comment by fotis400** [comment]
You can have this functionality by setting up some custom buttons.

Place in your config.yaml file the following:

```
controls:
- children:
  - command: M220 S%(percent)s
    input:
    - default: 100
      name: "Speed factor (%)"
      parameter: percent
    name: Set
    type: parametric_command
  - command: M221 S%(percent)s
    input:
    - default: 100
      name: "Extrude factor (%)"
      parameter: percent
    name: Set
    type: parametric_command
  name: Speed & Flow overrides
  type: section
```
